name: 洛谷打卡

on:
  schedule:
    - cron: '0 18 * * *'  # 每天 UTC 18:00，对应北京时间 2:00

jobs:
  punch:
    runs-on: ubuntu-latest

    steps:
      - name: 发送打卡请求
        run: |
          curl -X POST \
          -H "Accept: */*" \
          -H "Accept-Encoding: gzip, deflate, br" \
          -H "Accept-Language: zh-CN,zh;q=0.9" \
          -H "Content-Length: 0" \
          -H "Cookie: __client_id=${{ secrets.LUOGU_COOKIE }}; _uid=${{ secrets.LUOGU_UID }}" \
          -H "Origin: https://www.luogu.com.cn" \
          -H "Referer: https://www.luogu.com.cn/" \
          -H "Sec-Ch-Ua: \"Microsoft Edge\";v=\"117\", \"Not;A=Brand\";v=\"8\", \"Chromium\";v=\"117\"" \
          -H "Sec-Ch-Ua-Mobile: ?0" \
          -H "Sec-Ch-Ua-Platform: \"Windows\"" \
          -H "Sec-Fetch-Dest: empty" \
          -H "Sec-Fetch-Mode: cors" \
          -H "Sec-Fetch-Site: same-origin" \
          -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.31" \
          -H "X-Csrf-Token: ${{ secrets.LUOGU_X_CSRF_TOKEN }}" \
          -H "X-Requested-With: XMLHttpRequest" \
          https://www.luogu.com.cn/index/ajax_punch
