name: 洛谷自动打卡

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  Luogu_Auto_Punch:
    runs-on: windows-latest
    steps:
      - name: 下载打卡Python文件
        run: |
          Invoke-WebRequest blob:https://github.com/c1255559-4f46-463e-9491-676bac92277b -OutFile luogu_auto_punch.py
      - name: 安装库文件
        run: |
          pip install requests
      - name: 运行签到代码
        run: python .\luogu_auto_punch.py $Env:COOKIE
        env:
          COOKIE: ${{ secrets.COOKIE }}
